config/routes.rb
Rails.application.routes.draw do
  

  resources :admins_groups
  get 'group_roles' => "admins_groups#group_roles"
  post 'edit_group_roles' => "admins_groups#edit_group_roles"
  
  resources :users_banks
  resources :banks
  resources :groups_banks_limits
  resources :predefined_replies,:except => [:index]
  resources :predefined_reply_categories
  resources :users_groups
  resources :audit_logs
  resources :company_banks
  resources :admin_watchdogs,:only => [:create, :index, :show]
  resources :admin_logins,:only => [:create, :index, :show, :delete]
  
  resources :user_verifications
  resources :user_verfications
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :groups_banks_limits
      resources :users_groups
      resources :translations
      resources :watchdogs
      resources :users
      resources :admins
      resources :countries
      resources :affilate_programs
      resources :predefined_replies
      resources :predefined_reply_categories
      get "allreplies" => "predefined_replies#allreplies"
      post "users/create" => "users#create"
      get "homepage" => "users#homepage"
      post "confirmmail" => "users#confirmmail"
      post "resend_confirmmail" => "users#resend_confirmmail"
      get "two_factor" => "users#get_two_factor"
      post "two_factor" => "users#post_two_factor"
      get "statistics" => "users#statistics"
      get "lock_unlock_account" => "users#lock_unlock_account"
      get "send_confirmation_email" => "users#send_confirmation_email"
      get "change_confirmation_code" => "users#change_confirmation_code"
      get "confirm_google_code" => "users#confirm_google_code"
      get "set_otp_code" => "users#set_otp_code"
      get "user_log" => "watchdogs#user_log"
      get "active_sessions" => "logins#active_sessions"
      post 'auth_user' => 'authentication#authenticate_user'
      post "unlockaccount" => "authentication#unlockaccount"
      post "send_invitation_email" => "affilate_programs#send_invitation_email"
      post 'getEditToken' => 'authentication#getEditToken'
      resources :cards_logs
      resources :cards_categories
      resources :cards
      get "search" => "cards#search"
      post "search" => "cards#searchpost"
      get "buy_card" => "cards#buy_card" 
      get "cards_status" => "cards#cards_status"
      get "admin_add_note" => "cards#admin_add_note"
      post "admin_add_note" => "cards#admin_add_note"
      get "send_card" => "cards#send_card"
      post "send_card" => "cards#send_card"
      get "display_cards_categories" => "cards_categories#display_cards_categories"
      resources :addresses
      get "search_address" => "addresses#search"
      post "search_address" => "addresses#searchpost"
      get "delete_user_addresses" => "addresses#delete_user_addresses"
      get "user_addresses" => "addresses#user_addresses"
      get "send_sms" => "user_wallets#send_sms"
      post "send_sms_post" => "user_wallets#send_sms_post"
      post "verifysms_post" => "user_wallets#verifysms_post"
      get "verifysms" => "user_wallets#verifysms"
      get "wallets_status" => "user_wallets#wallets_status"
      get "transfer_balance" => "user_wallets#transfer_balance"
      post "transfer_balance" => "user_wallets#transfer_balancepost"
      resources :wallets_transfer_ratios
      resources :user_wallets
      resources :sms_logs
      resources :notifications
      resources :notifications_settings
      get "user_notifications" => "notifications#user_notifications"
      get "search_notifications" => "notifications#search"
      get "add_defualt_notifications" => "notifications_settings#add_defualt_notifications"
      resources :uploads
      resources :money_ops
      get "operations_status" => "money_ops#operations_status"
      resources :bank_accounts
      resources :ticket_departments
      resources :tickets,:except => [:edit]
      get "search_tickets" => "tickets#search"
      post "search_tickets" => "tickets#searchpost"
      post 'tickets/reply' => 'tickets#create_reply'
      resources :withdraws

    end
  end

  resources :withdraws
  resources :affilate_programs
  resources :countries
  resources :logins,:only => [:create, :index, :show, :delete]
  resources :verifications
  resources :watchdogs,:only => [:create, :index, :show]
  root "admins#homepage"
  get "confirmmail" => "users#confirmmail"
  get "unlockaccount" => "admins#unlockaccount"
  get "two_factor" => "admins#get_two_factor"
  post "two_factor" => "admins#post_two_factor"
  get "resend_two_factor" => "admins#resend_two_factor"
  get "user_log" => "watchdogs#user_log"
  get "audit_log" => "audit_logs#user_audit_log"
  get "admin_log" => "admin_watchdogs#admin_log"
  get "statistics" => "admins#statistics"
  get "lock_unlock_account" => "users#lock_unlock_account"
  get "users/search" => "users#search"
  get "admins/search" => "admins#search"
  get "userverifications/search" => "user_infos#search"
  get "nationalid_verifications/search" => "nationalid_verifications#search"
  get "address_verifications/search" => "address_verifications#search"
  get "selfie_verifications/search" => "selfie_verifications#search"






  get "active_sessions" => "logins#active_sessions"
  get "admin_active_sessions" => "admin_logins#admin_active_sessions"
  get "send_confirmation_email" => "admins#send_confirmation_email"
  get "change_confirmation_code" => "admins#change_confirmation_code"
  get "confirm_google_code" => "admins#confirm_google_code"
  match 'reset_expired_password', to: 'admins#reset_expired_password', via: %i(get patch post)
  resources :users,:except => [:new]
  resources :admins,:except => [:new]
  resources :user_infos
  resources :selfie_verifications,:except => [:new, :create]
  resources :address_verifications,:except => [:new, :create]
  resources :nationalid_verifications,:except => [:new, :create]



  #get "edit_password/:id" => "users#edit_password" , :as => "edit_password" 
  get "add_admin" => "admins#add_admin"
  post "add_admin" => "admins#add_admin_post"
  get "error_page" => "logins#error_page"
  get "lock_page" => "admin_logins#lock_page"
  post "lock_page" => "admin_logins#check_to_unlock"
  resources :cards_logs
  resources :cards_categories
  resources :cards
  get "search" => "cards#search"
  post "search" => "cards#searchpost"
  get "buy_card" => "cards#buy_card" 
  get "cards_status" => "cards#cards_status"
  get "admin_add_note" => "cards#admin_add_note"
  post "admin_add_note" => "cards#admin_add_note"
  get "send_card" => "cards#send_card"
  post "send_card" => "cards#send_card"
  get "display_cards_categories" => "cards_categories#display_cards_categories"
  resources :addresses
  get "search_address" => "addresses#search"
  post "search_address" => "addresses#searchpost"
  get "delete_user_addresses" => "addresses#delete_user_addresses"
  get "user_addresses" => "addresses#user_addresses"
  get "send_sms" => "user_wallets#send_sms"
  post "send_sms_post" => "user_wallets#send_sms_post"
  post "verifysms_post" => "user_wallets#verifysms_post"
  get "verifysms" => "user_wallets#verifysms"
  get "wallets_status" => "user_wallets#wallets_status"
  get "user_list_data" => "user_wallets#user_list_data"
  get "transfer_balance" => "user_wallets#transfer_balance"
  post "transfer_balance" => "user_wallets#transfer_balancepost"
  get "admin_add_balance" => "user_wallets#admin_add_balance"
  post "admin_add_balance_post" => "user_wallets#admin_add_balance_post"
  get "confirm_transfer" => "user_wallets#confirm_transfer"
  get "refund_transfer" => "user_wallets#refund_transfer"
  resources :wallets_transfer_ratios
  resources :user_wallets
  resources :users_wallets_transfers
  resources :sms_logs
  resources :notifications
  resources :notifications_settings
  get "user_notifications" => "notifications#user_notifications"
  get "search_notifications" => "notifications#search"
  get "search_notifications_settings" => "notifications_settings#search"
  get "add_defualt_notifications" => "notifications_settings#add_defualt_notifications"
  resources :uploads
  resources :money_ops
  get "operations_status" => "money_ops#operations_status"
  post "operations_status" => "money_ops#operations_status"
  get "remittance_operations" => "money_ops#remittance_operations"
  resources :bank_accounts
  resources :ticket_departments
  get 'tickets/statistics' => 'tickets#statistics'
  resources :tickets,:except => [:edit]
  get "search_tickets" => "tickets#search"
  post "search_tickets" => "tickets#searchpost"
  post "change_tickets_priority" => "tickets#changepriority"
  post "change_tickets_reminder" => "tickets#changereminder"
  post 'tickets/reply' => 'tickets#create_reply'
  post "change_ticket_department_status" => "ticket_departments#changestatus"
  resources :user_announcements
  resources :quick_payments
  get "link_check" => "quick_payments#link_check"
  get "quick_transfers" => "quick_payments#quick_transfers"

  get "user_bank_accounts" => "withdraws#user_bank_accounts"
  post "close_ticket" => "tickets#close_ticket"
  get "close_ticket" => "tickets#close_tickets"
  get "allreplies" => "predefined_replies#allreplies"
  get "replycontent" => "predefined_replies#replycontent"
  resources :blogs_categories
  resources :payers_blogs

  get "add_user" => "users#add_user"
  post "add_user" => "users#add_user_post"

  resources :translations
  get "change_locale" => "translations#change_locale"
  get "email_text" => "translations#email_text"
  
  resources :settings
  get "edit_settings" => "settings#edit_settings"
  get "mail_setting" => "settings#mail_setting"
  get "money_setting" => "settings#money_setting"
  get "payers_statistics" => "settings#payers_statistics"
  resources :errors_logs
  get "admins_errors_logs" => "errors_logs#admins_errors_logs"
  get "page_error" => "errors_logs#page_error"
  

  
  
  resources :passwords,
      controller: 'clearance/passwords',
      only: [:create, :new]

  resource :session,

app/models/predefined_reply.rb
class PredefinedReply < ApplicationRecord
    # belongs_to :predefined_reply_category ,:foreign_key => "id"
end

app/controllers/predefined_replies_controller.rb
class PredefinedRepliesController < ApplicationController
  before_action :set_predefined_reply, only: [:show, :edit, :update, :destroy]

  # GET /predefined_replies
  # GET /predefined_replies.json
  def index
    @predefined_replies = PredefinedReply.joins("INNER JOIN predefined_reply_categories ON predefined_reply_categories.id = predefined_replies.category_id").select("predefined_replies.*,predefined_reply_categories.name").all
    @predefined_reply_categories = PredefinedReplyCategory.all
  end

  # GET /predefined_replies/1
  # GET /predefined_replies/1.json
  def show
    @predefined_reply = PredefinedReply.joins("INNER JOIN predefined_reply_categories ON predefined_reply_categories.id = predefined_replies.category_id").select("predefined_replies.*,predefined_reply_categories.name").find(params[:id])

  end

  # GET /predefined_replies/new
  def new
    @predefined_reply = PredefinedReply.new
    @category = PredefinedReplyCategory.all
  end

  # GET /predefined_replies/1/edit
  def edit
    @category = PredefinedReplyCategory.all
  end

  # POST /predefined_replies
  # POST /predefined_replies.json
  def create
    @predefined_reply = PredefinedReply.new(predefined_reply_params)
    @category = PredefinedReplyCategory.all

    respond_to do |format|
      if @predefined_reply.save
        format.html { redirect_to predefined_reply_categories_url, notice: 'Predefined reply was successfully created.' }
        format.json { render :show, status: :created, location: predefined_reply_categories_url }
      else
        format.html { render :new }
        format.json { render json: @predefined_reply.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /predefined_replies/1
  # PATCH/PUT /predefined_replies/1.json
  def update
    respond_to do |format|
      if @predefined_reply.update(predefined_reply_params)
        format.html { redirect_to predefined_reply_categories_url, notice: 'Predefined reply was successfully updated.' }
        format.json { render :show, status: :ok, location: predefined_reply_categories_url }
      else
        format.html { render :edit }
        format.json { render json: @predefined_reply.errors, status: :unprocessable_entity }
      end
    end
  end

  def allreplies
    @category_id = params[:category_id].to_i
    @category_replies = PredefinedReply.where(:category_id => @category_id ).all
    render :json => {'category': @category_replies }
  end

  def replycontent
    @reply_id = params[:reply_id].to_i
    @replycontent = PredefinedReply.where(:id => @reply_id ).pluck(:content).first
    render :json => {'content': @replycontent }
  end

  # DELETE /predefined_replies/1
  # DELETE /predefined_replies/1.json
  def destroy
    @predefined_reply.destroy
    respond_to do |format|
      format.html { redirect_to predefined_reply_categories_url, notice: 'Predefined reply was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_predefined_reply
      @predefined_reply = PredefinedReply.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def predefined_reply_params
      params.require(:predefined_reply).permit(:title, :content, :category_id)
    end
end

app/helpers/predefined_replies_helper.rb
module PredefinedRepliesHelper
end

app/views/predefined_replies/_form.html.erb
<%= form_with(model: predefined_reply, local: true) do |form| %>
  <% if predefined_reply.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(predefined_reply.errors.count, "error") %> prohibited this predefined_reply from being saved:</h2>

      <ul>
      <% predefined_reply.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row group2">
    <label for="inputPassword3" class="col-sm-2 form-control-label ">Title</label>
    <div class="col-sm-10">
      <%= form.text_field :title, class: 'form-control subject'%>
    </div>
  </div>

  <div class="form-group row group2">
    <label for="inputPassword3" class="col-sm-2 form-control-label ">Content</label>
    <div class="col-sm-10">
      <%= form.text_field :content, class: 'form-control subject'%>
    </div>
  </div>

  <div class="form-group row group2">
    <%= form.label :category_id , class: "col-sm-2 form-control-label" %>
    <div class="col-sm-10">
    <select name="predefined_reply[category_id]" class="form-control c-select subject">
      <option disabled selected value >Select category</option>
      <%= @category.each do |category| %>
        <option value="<%= category.id %>"><%= category.name %></option>
      <% end %>
    </select>
</div>
  </div>
  <div class="actions">
    <%= form.submit class: "btn btn-fw primary" %>
  </div>
<% end %>

app/views/predefined_replies/edit.html.erb
<div class="padding">
    <div class="box">
        <div class="box-header">
             <h2>Editing Predefined Reply</h2>
        </div>
        <div class="box-divider m-0"></div>
            <div class="box-body">
                <%= form_with(model: @predefined_reply, local: true) do |form| %>
                <% if @predefined_reply.errors.any? %>
                    <div id="error_explanation">
                    <h2><%= pluralize(@predefined_reply.errors.count, "error") %> prohibited this predefined_reply from being saved:</h2>

                    <ul>
                    <% @predefined_reply.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                    </ul>
                    </div>
                <% end %>

                <div class="form-group row group2">
                    <label for="inputPassword3" class="col-sm-2 form-control-label ">Title</label>
                    <div class="col-sm-10">
                    <%= form.text_field :title, class: 'form-control subject'%>
                    </div>
                </div>

                <div class="form-group row group2">
                    <label for="inputPassword3" class="col-sm-2 form-control-label ">Content</label>
                    <div class="col-sm-10">
                    <%= form.text_field :content, class: 'form-control subject'%>
                    </div>
                </div>

                <div class="form-group row group2">
                    <%= form.label :category_id , class: "col-sm-2 form-control-label" %>
                    <div class="col-sm-10">
                    <select name="predefined_reply[category_id]" class="form-control c-select subject">
                    <%= @category.each do |category| %>
                        <option value="<%= category.id %>" <% if @predefined_reply.category_id == category.id  %> selected <% end %> ><%= category.name %></option>
                    <% end %>
                    </select>
                </div>
                </div>
                <div class="actions">
                    <%= form.submit class: "btn btn-fw primary" %>
                </div>
                <% end %>
            </div>
    </div>
    <%= link_to 'Show', @predefined_reply %> |
    <%= link_to 'Back', predefined_reply_categories_path %>
</div>

app/views/predefined_replies/index.html.erb
<div class="padding">
  <div class="box">
    <div class="box-header">
      <h6 class="m-b">Predefined Replies</h6>
    </div>
    <div class="row">
      <div class="col-sm-12">
        <div class="b-b b-primary nav-active-primary">
          <ul class="nav nav-tabs">
            <li class="nav-item">
              <a class="nav-link active" href data-toggle="tab" data-target="#tab4">Categories</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href data-toggle="tab" data-target="#tab5">Replies</a>
            </li>
          </ul>
        </div>
        <div class="tab-content p-a m-b-md">

          <div class="tab-pane animated fadeIn text-muted active" id="tab4">
              <div class="box-header box-header2"> <!-- class box-header2 for this style-->
                <% if current_user and current_user.roleid == 1 %>
                <%= link_to 'New Predefined Reply Category', new_predefined_reply_category_path, {:class => 'btn btn-fw accent accent2'}%>
                <% end %>
              </div>
              <div class="box-body">
                  Search: <input id="filter1" type="text" class="form-control input-sm w-auto inline m-r"/>
                  </div>
                    <div class="table-responsive table2"> <!-- class table2 for this style-->
                    <table class="table table-striped b-t" class="table m-b-none" ui-jp="footable" data-filter="#filter1" data-page-size="10">
                      <thead>
                        <tr id="td">
                          <th>Name</th>
                          <th colspan="3"></th>
                        </tr>
                      </thead>
                      <tbody>
                        <% @predefined_reply_categories.each do |predefined_reply_category| %>
                    <tr>
                      <td><%= predefined_reply_category.name %></td>
                      <td><%= link_to 'Show', predefined_reply_category %>-<%= link_to 'Edit', edit_predefined_reply_category_path(predefined_reply_category) %>-<%= link_to 'Destroy', predefined_reply_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    </tr>
                  <% end %>
                      </tbody>
                    </table>
                  </div>
                    <footer class="dker p-a">
                      <div class="row">
              
                        <div class="col-sm-4 text-right text-center-xs">
                        <tfoot class="hide-if-no-paging">
                        <tr>
                            <td colspan="5" class="text-center">
                                <ul class="pagination"></ul>
                            </td>
                        </tr>
                        </tfoot>
                      </div>
                      </div>
                    </footer>

          </div>

          <div class="tab-pane animated fadeIn text-muted" id="tab5">
              <div class="box-header box-header2"> <!-- class box-header2 for this style-->
                <% if current_user and current_user.roleid == 1 %>
                <%= link_to 'New Predefined Reply', new_predefined_reply_path, {:class => 'btn btn-fw accent accent2'}%>
                <% end %>
              </div>
              <div class="box-body">
                  Search: <input id="filter2" type="text" class="form-control input-sm w-auto inline m-r"/>
                  </div>
                    <div class="table-responsive table2"> <!-- class table2 for this style-->
                    <table class="table table-striped b-t" class="table m-b-none" ui-jp="footable" data-filter="#filter2" data-page-size="10">
                      <thead>
                        <tr id="td">
                          <th>Title</th>
                          <th>Content</th>
                          <th>Category</th>
                          <th colspan="3"></th>
                        </tr>
                      </thead>
                      <tbody>
                        <% @predefined_replies.each do |predefined_reply| %>
                          <tr>
                            <td><%= predefined_reply.title %></td>
                            <td><%= predefined_reply.content %></td>
                            <td><%= predefined_reply.name %></td>
                            <td><%= link_to 'Show', predefined_reply %>-<%= link_to 'Edit', edit_predefined_reply_path(predefined_reply) %>-<%= link_to 'Destroy', predefined_reply, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                          </tr>
                        <% end %>
                      </tbody>
                    </table>
                  </div>
                    <footer class="dker p-a">
                      <div class="row">
              
                        <div class="col-sm-4 text-right text-center-xs">
                        <tfoot class="hide-if-no-paging">
                        <tr>
                            <td colspan="5" class="text-center">
                                <ul class="pagination"></ul>
                            </td>
                        </tr>
                        </tfoot>
                      </div>
                      </div>
                    </footer>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/predefined_replies/new.html.erb
<div class="padding">
    <div class="box">
        <div class="box-header">
             <h2>New Predefined Reply</h2>
        </div>
        <div class="box-divider m-0"></div>
            <div class="box-body">
                <%= render 'form', predefined_reply: @predefined_reply %>
            </div>
    </div>
    <%= link_to 'Back', predefined_reply_categories_path %>
</div>
                

app/views/predefined_replies/show.html.erb
<div class="padding">
      <div class="box">
        <div class="box-header">
          <h3>Predefined Reply</h3>
        </div>
        <table class="table">
          <thead>
            <tr>
              <th>Title</th>
              <td><%= @predefined_reply.title %></td>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th>Content</th>
              <td> <%= @predefined_reply.content %></td>
            </tr>
            <tr>
              <th>Category</th>
              <td> <%= @predefined_reply.name %></td>
            </tr>
          </tbody>
        </table>
      </div>
      <%= link_to 'Edit', edit_predefined_reply_path(@predefined_reply) %> |
      <%= link_to 'Back', predefined_reply_categories_path %>
</div>