config/routes.rb
Rails.application.routes.draw do
  

  resources :admins_groups
  get 'group_roles' => "admins_groups#group_roles"
  post 'edit_group_roles' => "admins_groups#edit_group_roles"
  
  resources :users_banks
  resources :banks
  resources :groups_banks_limits
  resources :predefined_replies,:except => [:index]
  resources :predefined_reply_categories
  resources :users_groups
  resources :audit_logs
  resources :company_banks
  resources :admin_watchdogs,:only => [:create, :index, :show]
  resources :admin_logins,:only => [:create, :index, :show, :delete]
  
  resources :user_verifications
  resources :user_verfications
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :groups_banks_limits
      resources :users_groups
      resources :translations
      resources :watchdogs
      resources :users
      resources :admins
      resources :countries
      resources :affilate_programs
      resources :predefined_replies
      resources :predefined_reply_categories
      get "allreplies" => "predefined_replies#allreplies"
      post "users/create" => "users#create"
      get "homepage" => "users#homepage"
      post "confirmmail" => "users#confirmmail"
      post "resend_confirmmail" => "users#resend_confirmmail"
      get "two_factor" => "users#get_two_factor"
      post "two_factor" => "users#post_two_factor"
      get "statistics" => "users#statistics"
      get "lock_unlock_account" => "users#lock_unlock_account"
      get "send_confirmation_email" => "users#send_confirmation_email"
      get "change_confirmation_code" => "users#change_confirmation_code"
      get "confirm_google_code" => "users#confirm_google_code"
      get "set_otp_code" => "users#set_otp_code"
      get "user_log" => "watchdogs#user_log"
      get "active_sessions" => "logins#active_sessions"
      post 'auth_user' => 'authentication#authenticate_user'
      post "unlockaccount" => "authentication#unlockaccount"
      post "send_invitation_email" => "affilate_programs#send_invitation_email"
      post 'getEditToken' => 'authentication#getEditToken'
      resources :cards_logs
      resources :cards_categories
      resources :cards
      get "search" => "cards#search"
      post "search" => "cards#searchpost"
      get "buy_card" => "cards#buy_card" 
      get "cards_status" => "cards#cards_status"
      get "admin_add_note" => "cards#admin_add_note"
      post "admin_add_note" => "cards#admin_add_note"
      get "send_card" => "cards#send_card"
      post "send_card" => "cards#send_card"
      get "display_cards_categories" => "cards_categories#display_cards_categories"
      resources :addresses
      get "search_address" => "addresses#search"
      post "search_address" => "addresses#searchpost"
      get "delete_user_addresses" => "addresses#delete_user_addresses"
      get "user_addresses" => "addresses#user_addresses"
      get "send_sms" => "user_wallets#send_sms"
      post "send_sms_post" => "user_wallets#send_sms_post"
      post "verifysms_post" => "user_wallets#verifysms_post"
      get "verifysms" => "user_wallets#verifysms"
      get "wallets_status" => "user_wallets#wallets_status"
      get "transfer_balance" => "user_wallets#transfer_balance"
      post "transfer_balance" => "user_wallets#transfer_balancepost"
      resources :wallets_transfer_ratios
      resources :user_wallets
      resources :sms_logs
      resources :notifications
      resources :notifications_settings
      get "user_notifications" => "notifications#user_notifications"
      get "search_notifications" => "notifications#search"
      get "add_defualt_notifications" => "notifications_settings#add_defualt_notifications"
      resources :uploads
      resources :money_ops
      get "operations_status" => "money_ops#operations_status"
      resources :bank_accounts
      resources :ticket_departments
      resources :tickets,:except => [:edit]
      get "search_tickets" => "tickets#search"
      post "search_tickets" => "tickets#searchpost"
      post 'tickets/reply' => 'tickets#create_reply'
      resources :withdraws

    end
  end

  resources :withdraws
  resources :affilate_programs
  resources :countries
  resources :logins,:only => [:create, :index, :show, :delete]
  resources :verifications
  resources :watchdogs,:only => [:create, :index, :show]
  root "admins#homepage"
  get "confirmmail" => "users#confirmmail"
  get "unlockaccount" => "admins#unlockaccount"
  get "two_factor" => "admins#get_two_factor"
  post "two_factor" => "admins#post_two_factor"
  get "resend_two_factor" => "admins#resend_two_factor"
  get "user_log" => "watchdogs#user_log"
  get "audit_log" => "audit_logs#user_audit_log"
  get "admin_log" => "admin_watchdogs#admin_log"
  get "statistics" => "admins#statistics"
  get "lock_unlock_account" => "users#lock_unlock_account"
  get "users/search" => "users#search"
  get "admins/search" => "admins#search"
  get "userverifications/search" => "user_infos#search"
  get "nationalid_verifications/search" => "nationalid_verifications#search"
  get "address_verifications/search" => "address_verifications#search"
  get "selfie_verifications/search" => "selfie_verifications#search"






  get "active_sessions" => "logins#active_sessions"
  get "admin_active_sessions" => "admin_logins#admin_active_sessions"
  get "send_confirmation_email" => "admins#send_confirmation_email"
  get "change_confirmation_code" => "admins#change_confirmation_code"
  get "confirm_google_code" => "admins#confirm_google_code"
  match 'reset_expired_password', to: 'admins#reset_expired_password', via: %i(get patch post)
  resources :users,:except => [:new]
  resources :admins,:except => [:new]
  resources :user_infos
  resources :selfie_verifications,:except => [:new, :create]
  resources :address_verifications,:except => [:new, :create]
  resources :nationalid_verifications,:except => [:new, :create]



  #get "edit_password/:id" => "users#edit_password" , :as => "edit_password" 
  get "add_admin" => "admins#add_admin"
  post "add_admin" => "admins#add_admin_post"
  get "error_page" => "logins#error_page"
  get "lock_page" => "admin_logins#lock_page"
  post "lock_page" => "admin_logins#check_to_unlock"
  resources :cards_logs
  resources :cards_categories
  resources :cards
  get "search" => "cards#search"
  post "search" => "cards#searchpost"
  get "buy_card" => "cards#buy_card" 
  get "cards_status" => "cards#cards_status"
  get "admin_add_note" => "cards#admin_add_note"
  post "admin_add_note" => "cards#admin_add_note"
  get "send_card" => "cards#send_card"
  post "send_card" => "cards#send_card"
  get "display_cards_categories" => "cards_categories#display_cards_categories"
  resources :addresses
  get "search_address" => "addresses#search"
  post "search_address" => "addresses#searchpost"
  get "delete_user_addresses" => "addresses#delete_user_addresses"
  get "user_addresses" => "addresses#user_addresses"
  get "send_sms" => "user_wallets#send_sms"
  post "send_sms_post" => "user_wallets#send_sms_post"
  post "verifysms_post" => "user_wallets#verifysms_post"
  get "verifysms" => "user_wallets#verifysms"
  get "wallets_status" => "user_wallets#wallets_status"
  get "user_list_data" => "user_wallets#user_list_data"
  get "transfer_balance" => "user_wallets#transfer_balance"
  post "transfer_balance" => "user_wallets#transfer_balancepost"
  get "admin_add_balance" => "user_wallets#admin_add_balance"
  post "admin_add_balance_post" => "user_wallets#admin_add_balance_post"
  get "confirm_transfer" => "user_wallets#confirm_transfer"
  get "refund_transfer" => "user_wallets#refund_transfer"
  resources :wallets_transfer_ratios
  resources :user_wallets
  resources :users_wallets_transfers
  resources :sms_logs
  resources :notifications
  resources :notifications_settings
  get "user_notifications" => "notifications#user_notifications"
  get "search_notifications" => "notifications#search"
  get "search_notifications_settings" => "notifications_settings#search"
  get "add_defualt_notifications" => "notifications_settings#add_defualt_notifications"
  resources :uploads
  resources :money_ops
  get "operations_status" => "money_ops#operations_status"
  post "operations_status" => "money_ops#operations_status"
  get "remittance_operations" => "money_ops#remittance_operations"
  resources :bank_accounts
  resources :ticket_departments
  get 'tickets/statistics' => 'tickets#statistics'
  resources :tickets,:except => [:edit]
  get "search_tickets" => "tickets#search"
  post "search_tickets" => "tickets#searchpost"
  post "change_tickets_priority" => "tickets#changepriority"
  post "change_tickets_reminder" => "tickets#changereminder"
  post 'tickets/reply' => 'tickets#create_reply'
  post "change_ticket_department_status" => "ticket_departments#changestatus"
  resources :user_announcements
  resources :quick_payments
  get "link_check" => "quick_payments#link_check"
  get "quick_transfers" => "quick_payments#quick_transfers"

  get "user_bank_accounts" => "withdraws#user_bank_accounts"
  post "close_ticket" => "tickets#close_ticket"
  get "close_ticket" => "tickets#close_tickets"
  get "allreplies" => "predefined_replies#allreplies"
  get "replycontent" => "predefined_replies#replycontent"
  resources :blogs_categories
  resources :payers_blogs

  get "add_user" => "users#add_user"
  post "add_user" => "users#add_user_post"

  resources :translations
  get "change_locale" => "translations#change_locale"
  get "email_text" => "translations#email_text"
  
  resources :settings
  get "edit_settings" => "settings#edit_settings"
  get "mail_setting" => "settings#mail_setting"
  get "money_setting" => "settings#money_setting"
  get "payers_statistics" => "settings#payers_statistics"
  resources :errors_logs
  get "admins_errors_logs" => "errors_logs#admins_errors_logs"
  get "page_error" => "errors_logs#page_error"
  

  
  
  resources :passwords,
      controller: 'clearance/passwords',
      only: [:create, :new]

  resource :session,

app/models/groups_banks_limit.rb
class GroupsBanksLimit < ApplicationRecord
    enum bank_type: { local_bank: 1, electronic_bank: 2, digital_bank: 3 }
    validates_numericality_of :maximum_daily_withdraw, :maximum_monthly_withdraw, :maximum_daily_deposite, :maximum_monthly_deposite, :greater_than_or_equal_to => 0.0    

end

app/controllers/groups_banks_limits_controller.rb
class GroupsBanksLimitsController < ApplicationController
  before_action :set_groups_banks_limit, only: [:show, :edit, :update, :destroy]

  # GET /groups_banks_limits
  # GET /groups_banks_limits.json
  def index
    @groups_banks_limits = GroupsBanksLimit.all
  end

  # GET /groups_banks_limits/1
  # GET /groups_banks_limits/1.json
  def show
  end

  # GET /groups_banks_limits/new
  def new
    @groups_banks_limit = GroupsBanksLimit.new
  end

  # GET /groups_banks_limits/1/edit
  def edit
  end

  # POST /groups_banks_limits
  # POST /groups_banks_limits.json
  def create
    @groups_banks_limit = GroupsBanksLimit.new(groups_banks_limit_params)

    respond_to do |format|
      if @groups_banks_limit.save
        format.html { redirect_to @groups_banks_limit, notice: 'Groups banks limit was successfully created.' }
        format.json { render :show, status: :created, location: @groups_banks_limit }
      else
        format.html { render :new }
        format.json { render json: @groups_banks_limit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups_banks_limits/1
  # PATCH/PUT /groups_banks_limits/1.json
  def update
    respond_to do |format|
      if @groups_banks_limit.update(groups_banks_limit_params)
        format.html { redirect_to @groups_banks_limit, notice: 'Groups banks limit was successfully updated.' }
        format.json { render :show, status: :ok, location: @groups_banks_limit }
      else
        format.html { render :edit }
        format.json { render json: @groups_banks_limit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups_banks_limits/1
  # DELETE /groups_banks_limits/1.json
  def destroy
    @groups_banks_limit.destroy
    respond_to do |format|
      format.html { redirect_to groups_banks_limits_url, notice: 'Groups banks limit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_groups_banks_limit
      @groups_banks_limit = GroupsBanksLimit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def groups_banks_limit_params
      params.require(:groups_banks_limit).permit(:bank_type, :group_id, :maximum_daily_withdraw, :maximum_monthly_withdraw, :maximum_daily_deposite, :maximum_monthly_deposite)
    end
end

app/helpers/groups_banks_limits_helper.rb
module GroupsBanksLimitsHelper
end

app/views/groups_banks_limits/_form.html.erb
<%= form_with(model: groups_banks_limit, local: true) do |form| %>
  <% if groups_banks_limit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(groups_banks_limit.errors.count, "error") %> prohibited this groups_banks_limit from being saved:</h2>

      <ul>
      <% groups_banks_limit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :bank_type %>
    <%= form.number_field :bank_type %>
  </div>

  <div class="field">
    <%= form.label :group_id %>
    <%= form.number_field :group_id %>
  </div>

  <div class="field">
    <%= form.label :maximum_daily_withdraw %>
    <%= form.text_field :maximum_daily_withdraw %>
  </div>

  <div class="field">
    <%= form.label :maximum_monthly_withdraw %>
    <%= form.text_field :maximum_monthly_withdraw %>
  </div>

  <div class="field">
    <%= form.label :maximum_daily_deposite %>
    <%= form.text_field :maximum_daily_deposite %>
  </div>

  <div class="field">
    <%= form.label :maximum_monthly_deposite %>
    <%= form.text_field :maximum_monthly_deposite %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/groups_banks_limits/edit.html.erb
<h1>Editing Groups Banks Limit</h1>

<%= render 'form', groups_banks_limit: @groups_banks_limit %>

<%= link_to 'Show', @groups_banks_limit %> |
<%= link_to 'Back', groups_banks_limits_path %>

app/views/groups_banks_limits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Groups Banks Limits</h1>

<table>
  <thead>
    <tr>
      <th>Bank type</th>
      <th>Group</th>
      <th>Maximum daily withdraw</th>
      <th>Maximum monthly withdraw</th>
      <th>Maximum daily deposite</th>
      <th>Maximum monthly deposite</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups_banks_limits.each do |groups_banks_limit| %>
      <tr>
        <td><%= groups_banks_limit.bank_type %></td>
        <td><%= groups_banks_limit.group_id %></td>
        <td><%= groups_banks_limit.maximum_daily_withdraw %></td>
        <td><%= groups_banks_limit.maximum_monthly_withdraw %></td>
        <td><%= groups_banks_limit.maximum_daily_deposite %></td>
        <td><%= groups_banks_limit.maximum_monthly_deposite %></td>
        <td><%= link_to 'Show', groups_banks_limit %></td>
        <td><%= link_to 'Edit', edit_groups_banks_limit_path(groups_banks_limit) %></td>
        <td><%= link_to 'Destroy', groups_banks_limit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Groups Banks Limit', new_groups_banks_limit_path %>

app/views/groups_banks_limits/new.html.erb
<h1>New Groups Banks Limit</h1>

<%= render 'form', groups_banks_limit: @groups_banks_limit %>

<%= link_to 'Back', groups_banks_limits_path %>

app/views/groups_banks_limits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bank type:</strong>
  <%= @groups_banks_limit.bank_type %>
</p>

<p>
  <strong>Group:</strong>
  <%= @groups_banks_limit.group_id %>
</p>

<p>
  <strong>Maximum daily withdraw:</strong>
  <%= @groups_banks_limit.maximum_daily_withdraw %>
</p>

<p>
  <strong>Maximum monthly withdraw:</strong>
  <%= @groups_banks_limit.maximum_monthly_withdraw %>
</p>

<p>
  <strong>Maximum daily deposite:</strong>
  <%= @groups_banks_limit.maximum_daily_deposite %>
</p>

<p>
  <strong>Maximum monthly deposite:</strong>
  <%= @groups_banks_limit.maximum_monthly_deposite %>
</p>

<%= link_to 'Edit', edit_groups_banks_limit_path(@groups_banks_limit) %> |
<%= link_to 'Back', groups_banks_limits_path %>