config/routes.rb
Rails.application.routes.draw do
  

  resources :admins_groups
  get 'group_roles' => "admins_groups#group_roles"
  post 'edit_group_roles' => "admins_groups#edit_group_roles"
  
  resources :users_banks
  resources :banks
  resources :groups_banks_limits
  resources :predefined_replies,:except => [:index]
  resources :predefined_reply_categories
  resources :users_groups
  resources :audit_logs
  resources :company_banks
  resources :admin_watchdogs,:only => [:create, :index, :show]
  resources :admin_logins,:only => [:create, :index, :show, :delete]
  
  resources :user_verifications
  resources :user_verfications
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :groups_banks_limits
      resources :users_groups
      resources :translations
      resources :watchdogs
      resources :users
      resources :admins
      resources :countries
      resources :affilate_programs
      resources :predefined_replies
      resources :predefined_reply_categories
      get "allreplies" => "predefined_replies#allreplies"
      post "users/create" => "users#create"
      get "homepage" => "users#homepage"
      post "confirmmail" => "users#confirmmail"
      post "resend_confirmmail" => "users#resend_confirmmail"
      get "two_factor" => "users#get_two_factor"
      post "two_factor" => "users#post_two_factor"
      get "statistics" => "users#statistics"
      get "lock_unlock_account" => "users#lock_unlock_account"
      get "send_confirmation_email" => "users#send_confirmation_email"
      get "change_confirmation_code" => "users#change_confirmation_code"
      get "confirm_google_code" => "users#confirm_google_code"
      get "set_otp_code" => "users#set_otp_code"
      get "user_log" => "watchdogs#user_log"
      get "active_sessions" => "logins#active_sessions"
      post 'auth_user' => 'authentication#authenticate_user'
      post "unlockaccount" => "authentication#unlockaccount"
      post "send_invitation_email" => "affilate_programs#send_invitation_email"
      post 'getEditToken' => 'authentication#getEditToken'
      resources :cards_logs
      resources :cards_categories
      resources :cards
      get "search" => "cards#search"
      post "search" => "cards#searchpost"
      get "buy_card" => "cards#buy_card" 
      get "cards_status" => "cards#cards_status"
      get "admin_add_note" => "cards#admin_add_note"
      post "admin_add_note" => "cards#admin_add_note"
      get "send_card" => "cards#send_card"
      post "send_card" => "cards#send_card"
      get "display_cards_categories" => "cards_categories#display_cards_categories"
      resources :addresses
      get "search_address" => "addresses#search"
      post "search_address" => "addresses#searchpost"
      get "delete_user_addresses" => "addresses#delete_user_addresses"
      get "user_addresses" => "addresses#user_addresses"
      get "send_sms" => "user_wallets#send_sms"
      post "send_sms_post" => "user_wallets#send_sms_post"
      post "verifysms_post" => "user_wallets#verifysms_post"
      get "verifysms" => "user_wallets#verifysms"
      get "wallets_status" => "user_wallets#wallets_status"
      get "transfer_balance" => "user_wallets#transfer_balance"
      post "transfer_balance" => "user_wallets#transfer_balancepost"
      resources :wallets_transfer_ratios
      resources :user_wallets
      resources :sms_logs
      resources :notifications
      resources :notifications_settings
      get "user_notifications" => "notifications#user_notifications"
      get "search_notifications" => "notifications#search"
      get "add_defualt_notifications" => "notifications_settings#add_defualt_notifications"
      resources :uploads
      resources :money_ops
      get "operations_status" => "money_ops#operations_status"
      resources :bank_accounts
      resources :ticket_departments
      resources :tickets,:except => [:edit]
      get "search_tickets" => "tickets#search"
      post "search_tickets" => "tickets#searchpost"
      post 'tickets/reply' => 'tickets#create_reply'
      resources :withdraws

    end
  end

  resources :withdraws
  resources :affilate_programs
  resources :countries
  resources :logins,:only => [:create, :index, :show, :delete]
  resources :verifications
  resources :watchdogs,:only => [:create, :index, :show]
  root "admins#homepage"
  get "confirmmail" => "users#confirmmail"
  get "unlockaccount" => "admins#unlockaccount"
  get "two_factor" => "admins#get_two_factor"
  post "two_factor" => "admins#post_two_factor"
  get "resend_two_factor" => "admins#resend_two_factor"
  get "user_log" => "watchdogs#user_log"
  get "audit_log" => "audit_logs#user_audit_log"
  get "admin_log" => "admin_watchdogs#admin_log"
  get "statistics" => "admins#statistics"
  get "lock_unlock_account" => "users#lock_unlock_account"
  get "users/search" => "users#search"
  get "admins/search" => "admins#search"
  get "userverifications/search" => "user_infos#search"
  get "nationalid_verifications/search" => "nationalid_verifications#search"
  get "address_verifications/search" => "address_verifications#search"
  get "selfie_verifications/search" => "selfie_verifications#search"






  get "active_sessions" => "logins#active_sessions"
  get "admin_active_sessions" => "admin_logins#admin_active_sessions"
  get "send_confirmation_email" => "admins#send_confirmation_email"
  get "change_confirmation_code" => "admins#change_confirmation_code"
  get "confirm_google_code" => "admins#confirm_google_code"
  match 'reset_expired_password', to: 'admins#reset_expired_password', via: %i(get patch post)
  resources :users,:except => [:new]
  resources :admins,:except => [:new]
  resources :user_infos
  resources :selfie_verifications,:except => [:new, :create]
  resources :address_verifications,:except => [:new, :create]
  resources :nationalid_verifications,:except => [:new, :create]



  #get "edit_password/:id" => "users#edit_password" , :as => "edit_password" 
  get "add_admin" => "admins#add_admin"
  post "add_admin" => "admins#add_admin_post"
  get "error_page" => "logins#error_page"
  get "lock_page" => "admin_logins#lock_page"
  post "lock_page" => "admin_logins#check_to_unlock"
  resources :cards_logs
  resources :cards_categories
  resources :cards
  get "search" => "cards#search"
  post "search" => "cards#searchpost"
  get "buy_card" => "cards#buy_card" 
  get "cards_status" => "cards#cards_status"
  get "admin_add_note" => "cards#admin_add_note"
  post "admin_add_note" => "cards#admin_add_note"
  get "send_card" => "cards#send_card"
  post "send_card" => "cards#send_card"
  get "display_cards_categories" => "cards_categories#display_cards_categories"
  resources :addresses
  get "search_address" => "addresses#search"
  post "search_address" => "addresses#searchpost"
  get "delete_user_addresses" => "addresses#delete_user_addresses"
  get "user_addresses" => "addresses#user_addresses"
  get "send_sms" => "user_wallets#send_sms"
  post "send_sms_post" => "user_wallets#send_sms_post"
  post "verifysms_post" => "user_wallets#verifysms_post"
  get "verifysms" => "user_wallets#verifysms"
  get "wallets_status" => "user_wallets#wallets_status"
  get "user_list_data" => "user_wallets#user_list_data"
  get "transfer_balance" => "user_wallets#transfer_balance"
  post "transfer_balance" => "user_wallets#transfer_balancepost"
  get "admin_add_balance" => "user_wallets#admin_add_balance"
  post "admin_add_balance_post" => "user_wallets#admin_add_balance_post"
  get "confirm_transfer" => "user_wallets#confirm_transfer"
  get "refund_transfer" => "user_wallets#refund_transfer"
  resources :wallets_transfer_ratios
  resources :user_wallets
  resources :users_wallets_transfers
  resources :sms_logs
  resources :notifications
  resources :notifications_settings
  get "user_notifications" => "notifications#user_notifications"
  get "search_notifications" => "notifications#search"
  get "search_notifications_settings" => "notifications_settings#search"
  get "add_defualt_notifications" => "notifications_settings#add_defualt_notifications"
  resources :uploads
  resources :money_ops
  get "operations_status" => "money_ops#operations_status"
  post "operations_status" => "money_ops#operations_status"
  get "remittance_operations" => "money_ops#remittance_operations"
  resources :bank_accounts
  resources :ticket_departments
  get 'tickets/statistics' => 'tickets#statistics'
  resources :tickets,:except => [:edit]
  get "search_tickets" => "tickets#search"
  post "search_tickets" => "tickets#searchpost"
  post "change_tickets_priority" => "tickets#changepriority"
  post "change_tickets_reminder" => "tickets#changereminder"
  post 'tickets/reply' => 'tickets#create_reply'
  post "change_ticket_department_status" => "ticket_departments#changestatus"
  resources :user_announcements
  resources :quick_payments
  get "link_check" => "quick_payments#link_check"
  get "quick_transfers" => "quick_payments#quick_transfers"

  get "user_bank_accounts" => "withdraws#user_bank_accounts"
  post "close_ticket" => "tickets#close_ticket"
  get "close_ticket" => "tickets#close_tickets"
  get "allreplies" => "predefined_replies#allreplies"
  get "replycontent" => "predefined_replies#replycontent"
  resources :blogs_categories
  resources :payers_blogs

  get "add_user" => "users#add_user"
  post "add_user" => "users#add_user_post"

  resources :translations
  get "change_locale" => "translations#change_locale"
  get "email_text" => "translations#email_text"
  
  resources :settings
  get "edit_settings" => "settings#edit_settings"
  get "mail_setting" => "settings#mail_setting"
  get "money_setting" => "settings#money_setting"
  get "payers_statistics" => "settings#payers_statistics"
  resources :errors_logs
  get "admins_errors_logs" => "errors_logs#admins_errors_logs"
  get "page_error" => "errors_logs#page_error"
  

  
  
  resources :passwords,
      controller: 'clearance/passwords',
      only: [:create, :new]

  resource :session,

app/models/money_op.rb
class MoneyOp < ApplicationRecord
    validates_uniqueness_of :opid
    before_save :default_values
    belongs_to :user ,:foreign_key => "user_id"

    # Add default value to opid before save
    def default_values
        self.opid ||= "PY"+[*('A'..'Z'),*('0'..'9')].to_a.shuffle[0,10].join
    end
end

app/views/money_ops/_form.html.erb
<%= form_with(model: money_op, local: true) do |form| %>
  <% if money_op.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(money_op.errors.count, "error") %> prohibited this money_op from being saved:</h2>

      <ul>
      <% money_op.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :type %>
    <%= form.select :optype,options_for_select([['Wallet transfer',1],['Receive',2],['Withdraw',3],['Remittance',4]]),  {:include_blank => 'select type'} %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

  <div class="field">
    <%= form.label :payment_gateway %>
    <%= form.number_field :payment_gateway %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status,options_for_select([['Pending',0],['Compeleted',1]]),  {:include_blank => 'select status'} %>
  </div>

  <div class="field">
    <%= form.label :payment_date %>
    <%= form.datetime_select :payment_date %>
  </div>

  <div class="field">
    <%= form.label :paymentid %>
    <%= form.number_field :payment_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/money_ops/index.html.erb
<div class="direct-chat-msg right right2"> <!--class right2 for this style-->
  <div class="direct-chat-text direct2 " data-lrchatext-msgid="3">List of all money operartions</div> <!--class direct2 for this style-->
  <%= link_to 'New Money Op', new_money_op_path, :class => "btn btn-fw accent accent2" %>
</div>
<div class="padding">
  <div class="box">
    <div class="table-responsive table2">
      <table class="table m-b-none" ui-jp="footable" data-filter="#filter" data-page-size="10">
        <thead>
          <tr>
            <th>UserName</th>
            <th>Operartion id</th>
            <th>Type</th>
            <th>Amount</th>            
            <th>Status</th>
            <th>Payment date</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @money_ops.each do |money_op| %>
            <tr>
              <td><%= money_op.user.firstname + " " + money_op.user.lastname %></td>
              <td><%= money_op.opid %></td>
              <% if money_op.optype == 1 %>
              <td><%= "Wallet transfer" %></td>
              <% elsif money_op.optype == 2 %>
              <td><%= "Receive" %></td>
              <% elsif money_op.optype == 3 %>
              <td><%= "Withdraw" %></td>
              <% elsif money_op.optype == 4 %>
              <td><%= "Remittance" %></td>
              <% end %>
              <% if money_op.amount != nil %>
              <td><%= money_op.amount.round(2) %></td>
              <% else %>
              <td><%= "-" %></td>
              <% end %>              
              <% if money_op.status == 0 %>
                <td data-value="3"><span class="label" title="Disabled">Pending</span></td>
              <% elsif money_op.status == 1 %>
                <td data-value="2"><span class="label success" title="Active">Compeleted</span></td>
              <% elsif money_op.status == 2 %>
                <td data-value="1"><span class="label" title="Disabled">Cancelled</span></td>
              <% end %>
              <td><%= money_op.payment_date %></td>            
              <td><%= link_to 'Show', money_op, :class => "md-btn md-flat m-b-sm w-xs text-success" %></td>                
            </tr>
          <% end %>            
        </tbody>
        <tfoot class="hide-if-no-paging">
          <tr>
            <td colspan="5" class="text-center">
              <ul class="pagination"></ul>
            </td>
          </tr>
        </tfoot>
      </table>
    </div>
  </div>
</div>

app/views/money_ops/new.html.erb
<div class="padding">
    <div class="box">
        <div class="box-header">
             <h2>New Money Operation</h2>
        </div>
        <div class="box-divider m-0"></div>
            <div class="box-body">
                <%= form_with(model: @money_op, local: true) do |form| %>
                    <% if @money_op.errors.any? %>
                         <div id="error_explanation">
                             <%= pluralize(@money_op.errors.count, "error") %> prohibited this money op from being saved: 
                             <ul>
                                <% @money_op.errors.full_messages.each do |message| %>
                                   <li><%= message %></li>
                                <% end %>
                             </ul>
                         </div>
                    <% end %>                                       
                    <div class="form-group row">
                    <label class="col-sm-2 form-control-label">Operation type</label>
                       <div class="col-sm-10">
                       <%= form.select :optype,options_for_select([['Sent',1],['Receive',2],['Withdraw',3],['Remittance',4]]),  {:include_blank => 'select type'},{:class => 'form-control c-select'} %>
                       </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 form-control-label">Amount</label>
                            <div class="col-sm-10">
                                <%= form.text_field :amount , class: 'form-control' , :required => true %>
                            </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 form-control-label">Fees</label>
                            <div class="col-sm-10">
                                <%= form.text_field :fees , class: 'form-control' , :required => true %>
                            </div>
                    </div>
                    <div class="form-group row">
                    <label class="col-sm-2 form-control-label">Payment Gateway</label>
                        <div class="col-sm-10">
                            <%= form.text_field :payment_gateway , class: 'form-control' , :required => true %>
                        </div>
                    </div>
                    <div class="form-group row">
                    <label class="col-sm-2 form-control-label">Status</label>
                       <div class="col-sm-10">
                       <%= form.select :status,options_for_select([['Pending',0],['Compeleted',1]]),  {:include_blank => 'select status'} ,{:class => 'form-control c-select'} %>
                       </div>
                    </div>
                    <div class="form-group row">
                    <label class="col-sm-2 form-control-label">Payment Date</label>
                        <div class="col-sm-10">
                            <%= form.date_field :payment_date , class: 'form-control' , :required => true %>
                        </div>
                    </div>
                    <div class="form-group row">
                    <label class="col-sm-2 form-control-label">Payment ID</label>
                        <div class="col-sm-10">
                            <%= form.text_field :payment_id, type: 'number' , class: 'form-control', :required => true %>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 form-control-label">User ID</label>
                            <div class="col-sm-10">
                                <%= form.text_field :user_id, type: 'number' , class: 'form-control', :required => true %>
                            </div>
                    </div>

                    <div class="form-group row m-t-md">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-fw primary" id="submit" >Submit</button>
                        </div>
                    </div>
                <% end %>
            </div>
    </div>
    <%= link_to 'Back', money_ops_path %>
</div>
</div>

app/views/money_ops/remittance_operations.html.erb
<!-- ############ PAGE START-->
<div class="direct-chat-msg right right2"> <!--class right2 for this style-->
  <div class="direct-chat-text direct2 " data-lrchatext-msgid="3">Remittance Operartions</div> <!--class direct2 for this style-->
    <% if current_user and current_user.roleid == 1 %>
      <%= link_to 'New Card', new_card_path, {:class => 'btn btn-fw accent accent2'}%>
    <% end %>
</div>
<div class="padding">
  <div class="box">
    <div class="table-responsive table2">
      <table class="table m-b-none" ui-jp="footable" data-filter="#filter" data-page-size="5">
        <thead>
          <tr>
            <th>User id</th>
            <th>UserName</th>
            <th>Operartion id</th>
            <th>Card Num</th>
            <th>Amount</th>
            <th>Fees</th>
            <th>Payment gateway</th>
            <th data-hide="phone">Status</th>
            <th>Payment date</th>
            <th colspan="1"></th>
          </tr>
        </thead>
        <tbody>
        <% @operations.each do |operation| %>
          <tr>
            <td><%= operation.user_id %></td>
            <td><%= operation.user.firstname + " " + operation.user.lastname %></td>
            <td><%= operation.opid %></td>
            <% if operation.status == 3 %>
            <td><%= "****-****-****-****" %></td>
            <% else %>
            <td><%= operation.number.scan(/.{1,4}/).join('-') %></td>
            <% end %>
            <td><%= operation.amount %></td>
            <td><%= operation.fees %></td>
            <td><%= operation.payment_gateway %></td>
            <% if operation.status == 1 %>
            <td><span class="label success" title="Active">Active</span></td>
            <% elsif operation.status == 2 %>
            <td><span class="label success" title="Active">Charged</span></td>
            <% elsif operation.status == 3 %>
                <td><span class="label" title="Disabled">Pending</span></td>
            <% elsif operation.status == 4 %>
                <td><span class="label" title="Disabled">Cancelled</span></td>
            <% end %>
            <td><%= operation.payment_date %></td>
            <td><%= link_to 'Show', operation,:class => "md-btn md-flat m-b-sm w-xs text-success" %></td>
          </tr>
          <% end %>
          
        </tbody>
        <tfoot class="hide-if-no-paging">
          <tr>
              <td colspan="5" class="text-center">
                  <ul class="pagination"></ul>
              </td>
          </tr>
        </tfoot>
      </table>
    </div>
  </div>
</div>

<!-- ############ PAGE END-->

app/views/money_ops/show.html.erb
<div class="padding">
  
      <div class="box">
        <div class="box-header">
          <h3>Money Operation</h3>
        </div>
        <table class="table">
          <thead>
            <tr>
              <th>UserName</th>
              <td><%= @money_op.user.firstname + " " + @money_op.user.lastname  %></td>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th>User ID</th>
              <td> <%= @money_op.user_id %></td>
          </tr>
          <tr>
              <th>Operaion ID</th>
              <td><%= @money_op.opid %></td>
          </tr>
          <tr>
          <th>Operaion Type</th>
          <% if @money_op.optype == 1 %>
          <td><%= "Wallet transfer" %></td>
          <% elsif @money_op.optype == 2 %>
          <td><%= "Receive" %></td>
          <% elsif @money_op.optype == 3 %>
          <td><%= "Withdraw" %></td>
          <% elsif @money_op.optype == 4 %>
          <td><%= "Remittance" %></td>
          <% end %>
          </tr>
          <tr>
            <th>Amount</th>
            <td>  <% if @money_op.amount != nil %>
            <%= @money_op.amount.round(2) %>
            <% else %>
            <%= "-" %>
            <% end %></td>
          </tr>
          <tr>
            <th>Fees</th>
            <td>  <% if @money_op.fees != nil %>
            <%= @money_op.fees.round(2) %>
            <% else %>
            <%= "-" %>
            <% end %></td>
          </tr>

          <% if (@money_op.optype == 4) %>
           <tr>
            <th>Card original value</th>
            <td><%= @remittance_data.value %></td>
          </tr>
          <tr>
            <th>Card Net Value </th>
            <td><%= @remittance_data.net_value %></td>
          </tr>
            <% if @remittance_data.value.to_f != @remittance_data.net_value.to_f %>
              <tr>
                <th>payers deposit expenses </th>
                <td><%= (@remittance_data.value.to_f - @remittance_data.net_value.to_f).round(2) %></td>
              </tr>
            <% end %>
          <% end %>




          <tr>
            <th>Payment Gateway</th>
            <td> <%= @money_op.payment_gateway %></td>
          </tr>
          <tr>
          <th>Status</th>
                 
            <% if @money_op.optype == 4 && @money_op.status == 0 %>
                <%= form_for :operations_status ,:url => operations_status_path,:html => { :multipart => true } do |f| %>
                        <%=  f.hidden_field :id, :value => @money_op.id %>
                        <td><%= f.select :status,options_for_select([['Pending',0],['Compeleted',1],['Cancelled',2]]),  {:selected => @money_op.status , :required => true},{:class => "label"} %>
                        <button type="submit" class="label success" id="submit" >Submit</button></td>
                <% end %>
          
            <% else %>

              <% if @money_op.status == 0 %>
              <td><span class="label"><%= "Pending" %></span></td>
              <% elsif @money_op.status == 1 %>
              <td><span class="label success"><%= "Compeleted" %></span></td>
              <% elsif @money_op.status == 2 %>
              <td><span class="label"><%= "Cancelled" %></span></td>
              <% end %>

          <% end %>
          </tr>
          <tr>
            <th>Payment Date</th>
            <td><%= @money_op.payment_date %></td>
          </tr>
          <% if @money_op.payment_id != nil %> 
          <tr>
            <th>Payment ID</th>
            <td><%= @money_op.payment_id %></td>
          </tr>
          <% end %>
          <% if @bank_type == "local_bank" %>
            <% if @remittance_data.user_account_number != nil %>
              <tr>
                <th>Bank Account Number</th>
                <td><%= @remittance_data.user_account_number %></td>
              </tr>
            <% end %>

            <% if @remittance_data.note != nil %>
              <tr>
                <th>Note</th>
                <td><%= @remittance_data.note %></td>
              </tr>
            <% end %>

            <% if @remittance_data.payment_receipt.attached? %>
              <tr>
                <th>Attachment</th>
                <td><%= link_to image_tag(@remittance_data.payment_receipt.variant(resize: "100x100")),@remittance_data.payment_receipt %></td>
              </tr>
            <% end %>
          <% end %>

          <% if @money_op.admin_note != nil %>
          <tr>
            <th>Admin Note</th>
            <td><%= @money_op.admin_note %></td>
          </tr>
          <% end %>
          </tbody>
        </table>
     
      <% if (@money_op.optype == 3 || @money_op.optype == 4) && @money_op.status == 0 %>
        <div class="box-body">
            <%= form_for :admin_add_note ,:url => admin_add_note_path,:html => { :multipart => true } do |f| %>
                    <%=  f.hidden_field :operation_id, :value => @money_op.opid %>
                    <div class="form-group row">
                        <label class="col-sm-2 form-control-label">Send Note To User</label>
                        <div class="col-sm-10">
                            <%= f.text_area :admin_note , class: 'form-control' , :required => true %>
                        </div>
                    </div>

                  <div class="form-group row m-t-md">
                      <div class="col-sm-offset-2 col-sm-10">
                          <button type="submit" class="btn btn-fw primary" id="submit" >Submit</button>
                      </div>
                  </div>
            <% end %>
        </div>
      <% end %>
      </div>
      <%= link_to 'Back', money_ops_path %>
      
</div>