config/routes.rb
Rails.application.routes.draw do
  

  resources :admins_groups
  get 'group_roles' => "admins_groups#group_roles"
  post 'edit_group_roles' => "admins_groups#edit_group_roles"
  
  resources :users_banks
  resources :banks
  resources :groups_banks_limits
  resources :predefined_replies,:except => [:index]
  resources :predefined_reply_categories
  resources :users_groups
  resources :audit_logs
  resources :company_banks
  resources :admin_watchdogs,:only => [:create, :index, :show]
  resources :admin_logins,:only => [:create, :index, :show, :delete]
  
  resources :user_verifications
  resources :user_verfications
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :groups_banks_limits
      resources :users_groups
      resources :translations
      resources :watchdogs
      resources :users
      resources :admins
      resources :countries
      resources :affilate_programs
      resources :predefined_replies
      resources :predefined_reply_categories
      get "allreplies" => "predefined_replies#allreplies"
      post "users/create" => "users#create"
      get "homepage" => "users#homepage"
      post "confirmmail" => "users#confirmmail"
      post "resend_confirmmail" => "users#resend_confirmmail"
      get "two_factor" => "users#get_two_factor"
      post "two_factor" => "users#post_two_factor"
      get "statistics" => "users#statistics"
      get "lock_unlock_account" => "users#lock_unlock_account"
      get "send_confirmation_email" => "users#send_confirmation_email"
      get "change_confirmation_code" => "users#change_confirmation_code"
      get "confirm_google_code" => "users#confirm_google_code"
      get "set_otp_code" => "users#set_otp_code"
      get "user_log" => "watchdogs#user_log"
      get "active_sessions" => "logins#active_sessions"
      post 'auth_user' => 'authentication#authenticate_user'
      post "unlockaccount" => "authentication#unlockaccount"
      post "send_invitation_email" => "affilate_programs#send_invitation_email"
      post 'getEditToken' => 'authentication#getEditToken'
      resources :cards_logs
      resources :cards_categories
      resources :cards
      get "search" => "cards#search"
      post "search" => "cards#searchpost"
      get "buy_card" => "cards#buy_card" 
      get "cards_status" => "cards#cards_status"
      get "admin_add_note" => "cards#admin_add_note"
      post "admin_add_note" => "cards#admin_add_note"
      get "send_card" => "cards#send_card"
      post "send_card" => "cards#send_card"
      get "display_cards_categories" => "cards_categories#display_cards_categories"
      resources :addresses
      get "search_address" => "addresses#search"
      post "search_address" => "addresses#searchpost"
      get "delete_user_addresses" => "addresses#delete_user_addresses"
      get "user_addresses" => "addresses#user_addresses"
      get "send_sms" => "user_wallets#send_sms"
      post "send_sms_post" => "user_wallets#send_sms_post"
      post "verifysms_post" => "user_wallets#verifysms_post"
      get "verifysms" => "user_wallets#verifysms"
      get "wallets_status" => "user_wallets#wallets_status"
      get "transfer_balance" => "user_wallets#transfer_balance"
      post "transfer_balance" => "user_wallets#transfer_balancepost"
      resources :wallets_transfer_ratios
      resources :user_wallets
      resources :sms_logs
      resources :notifications
      resources :notifications_settings
      get "user_notifications" => "notifications#user_notifications"
      get "search_notifications" => "notifications#search"
      get "add_defualt_notifications" => "notifications_settings#add_defualt_notifications"
      resources :uploads
      resources :money_ops
      get "operations_status" => "money_ops#operations_status"
      resources :bank_accounts
      resources :ticket_departments
      resources :tickets,:except => [:edit]
      get "search_tickets" => "tickets#search"
      post "search_tickets" => "tickets#searchpost"
      post 'tickets/reply' => 'tickets#create_reply'
      resources :withdraws

    end
  end

  resources :withdraws
  resources :affilate_programs
  resources :countries
  resources :logins,:only => [:create, :index, :show, :delete]
  resources :verifications
  resources :watchdogs,:only => [:create, :index, :show]
  root "admins#homepage"
  get "confirmmail" => "users#confirmmail"
  get "unlockaccount" => "admins#unlockaccount"
  get "two_factor" => "admins#get_two_factor"
  post "two_factor" => "admins#post_two_factor"
  get "resend_two_factor" => "admins#resend_two_factor"
  get "user_log" => "watchdogs#user_log"
  get "audit_log" => "audit_logs#user_audit_log"
  get "admin_log" => "admin_watchdogs#admin_log"
  get "statistics" => "admins#statistics"
  get "lock_unlock_account" => "users#lock_unlock_account"
  get "users/search" => "users#search"
  get "admins/search" => "admins#search"
  get "userverifications/search" => "user_infos#search"
  get "nationalid_verifications/search" => "nationalid_verifications#search"
  get "address_verifications/search" => "address_verifications#search"
  get "selfie_verifications/search" => "selfie_verifications#search"






  get "active_sessions" => "logins#active_sessions"
  get "admin_active_sessions" => "admin_logins#admin_active_sessions"
  get "send_confirmation_email" => "admins#send_confirmation_email"
  get "change_confirmation_code" => "admins#change_confirmation_code"
  get "confirm_google_code" => "admins#confirm_google_code"
  match 'reset_expired_password', to: 'admins#reset_expired_password', via: %i(get patch post)
  resources :users,:except => [:new]
  resources :admins,:except => [:new]
  resources :user_infos
  resources :selfie_verifications,:except => [:new, :create]
  resources :address_verifications,:except => [:new, :create]
  resources :nationalid_verifications,:except => [:new, :create]



  #get "edit_password/:id" => "users#edit_password" , :as => "edit_password" 
  get "add_admin" => "admins#add_admin"
  post "add_admin" => "admins#add_admin_post"
  get "error_page" => "logins#error_page"
  get "lock_page" => "admin_logins#lock_page"
  post "lock_page" => "admin_logins#check_to_unlock"
  resources :cards_logs
  resources :cards_categories
  resources :cards
  get "search" => "cards#search"
  post "search" => "cards#searchpost"
  get "buy_card" => "cards#buy_card" 
  get "cards_status" => "cards#cards_status"
  get "admin_add_note" => "cards#admin_add_note"
  post "admin_add_note" => "cards#admin_add_note"
  get "send_card" => "cards#send_card"
  post "send_card" => "cards#send_card"
  get "display_cards_categories" => "cards_categories#display_cards_categories"
  resources :addresses
  get "search_address" => "addresses#search"
  post "search_address" => "addresses#searchpost"
  get "delete_user_addresses" => "addresses#delete_user_addresses"
  get "user_addresses" => "addresses#user_addresses"
  get "send_sms" => "user_wallets#send_sms"
  post "send_sms_post" => "user_wallets#send_sms_post"
  post "verifysms_post" => "user_wallets#verifysms_post"
  get "verifysms" => "user_wallets#verifysms"
  get "wallets_status" => "user_wallets#wallets_status"
  get "user_list_data" => "user_wallets#user_list_data"
  get "transfer_balance" => "user_wallets#transfer_balance"
  post "transfer_balance" => "user_wallets#transfer_balancepost"
  get "admin_add_balance" => "user_wallets#admin_add_balance"
  post "admin_add_balance_post" => "user_wallets#admin_add_balance_post"
  get "confirm_transfer" => "user_wallets#confirm_transfer"
  get "refund_transfer" => "user_wallets#refund_transfer"
  resources :wallets_transfer_ratios
  resources :user_wallets
  resources :users_wallets_transfers
  resources :sms_logs
  resources :notifications
  resources :notifications_settings
  get "user_notifications" => "notifications#user_notifications"
  get "search_notifications" => "notifications#search"
  get "search_notifications_settings" => "notifications_settings#search"
  get "add_defualt_notifications" => "notifications_settings#add_defualt_notifications"
  resources :uploads
  resources :money_ops
  get "operations_status" => "money_ops#operations_status"
  post "operations_status" => "money_ops#operations_status"
  get "remittance_operations" => "money_ops#remittance_operations"
  resources :bank_accounts
  resources :ticket_departments
  get 'tickets/statistics' => 'tickets#statistics'
  resources :tickets,:except => [:edit]
  get "search_tickets" => "tickets#search"
  post "search_tickets" => "tickets#searchpost"
  post "change_tickets_priority" => "tickets#changepriority"
  post "change_tickets_reminder" => "tickets#changereminder"
  post 'tickets/reply' => 'tickets#create_reply'
  post "change_ticket_department_status" => "ticket_departments#changestatus"
  resources :user_announcements
  resources :quick_payments
  get "link_check" => "quick_payments#link_check"
  get "quick_transfers" => "quick_payments#quick_transfers"

  get "user_bank_accounts" => "withdraws#user_bank_accounts"
  post "close_ticket" => "tickets#close_ticket"
  get "close_ticket" => "tickets#close_tickets"
  get "allreplies" => "predefined_replies#allreplies"
  get "replycontent" => "predefined_replies#replycontent"
  resources :blogs_categories
  resources :payers_blogs

  get "add_user" => "users#add_user"
  post "add_user" => "users#add_user_post"

  resources :translations
  get "change_locale" => "translations#change_locale"
  get "email_text" => "translations#email_text"
  
  resources :settings
  get "edit_settings" => "settings#edit_settings"
  get "mail_setting" => "settings#mail_setting"
  get "money_setting" => "settings#money_setting"
  get "payers_statistics" => "settings#payers_statistics"
  resources :errors_logs
  get "admins_errors_logs" => "errors_logs#admins_errors_logs"
  get "page_error" => "errors_logs#page_error"
  

  
  
  resources :passwords,
      controller: 'clearance/passwords',
      only: [:create, :new]

  resource :session,

app/models/admins_group.rb
class AdminsGroup < ApplicationRecord
    has_many :admin ,:foreign_key => "roleid"
    has_many :admingroups_roles
end

app/controllers/admins_groups_controller.rb
class AdminsGroupsController < ApplicationController
  before_action :set_admins_group, only: [:show, :edit, :update, :destroy]

  # GET /admins_groups
  # GET /admins_groups.json
  def index
    @admins_groups = AdminsGroup.all
  end

  # GET /admins_groups/1
  # GET /admins_groups/1.json
  def show
  end

  # GET /admins_groups/new
  def new
    @admins_group = AdminsGroup.new
  end

  # GET /admins_groups/1/edit
  def edit
  end

  # POST /admins_groups
  # POST /admins_groups.json
  def create
    @admins_group = AdminsGroup.new(admins_group_params)

    respond_to do |format|
      if @admins_group.save
        format.html { redirect_to @admins_group, notice: 'Admins group was successfully created.' }
        format.json { render :show, status: :created, location: @admins_group }
      else
        format.html { render :new }
        format.json { render json: @admins_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admins_groups/1
  # PATCH/PUT /admins_groups/1.json
  def update
    respond_to do |format|
      if @admins_group.update(admins_group_params)
        format.html { redirect_to @admins_group, notice: 'Admins group was successfully updated.' }
        format.json { render :show, status: :ok, location: @admins_group }
      else
        format.html { render :edit }
        format.json { render json: @admins_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admins_groups/1
  # DELETE /admins_groups/1.json
  def destroy
    @admins_group.destroy
    respond_to do |format|
      format.html { redirect_to admins_groups_url, notice: 'Admins group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def group_roles
    if params[:id].to_i == 1
      redirect_to(admins_groups_path, notice: 'you cannot edit roles for super admin group.')
    else
      @roles = Role.all.group(:caption)
      @assignments = AdmingroupsRole.where(:admins_group_id => params[:id]).all
      @group_name = AdminsGroup.where(:id => params[:id]).first.name
    end 
  end

  def edit_group_roles
    if AdmingroupsRole.where(:admins_group_id => params[:groupid]).blank?
      if params[:role]
        params[:role].each do |role|
          AdmingroupsRole.create(:admins_group_id => params[:groupid],:role_id => role )
        end
      end
        redirect_back fallback_location: root_path, notice: 'Group roles was successfully created'
    else
      if params[:role]
        AdmingroupsRole.where(:admins_group_id => params[:groupid]).destroy_all
        params[:role].each do |role|
          AdmingroupsRole.create(:admins_group_id => params[:groupid],:role_id => role )
        end
      end
      redirect_back fallback_location: root_path, notice: 'Group roles was successfully updated'
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admins_group
      @admins_group = AdminsGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admins_group_params
      params.require(:admins_group).permit(:name)
    end
end

app/helpers/admins_groups_helper.rb
module AdminsGroupsHelper
end

app/views/admins_groups/_form.html.erb
<%= form_with(model: admins_group, local: true) do |form| %>
  <% if admins_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admins_group.errors.count, "error") %> prohibited this admins_group from being saved:</h2>

      <ul>
      <% admins_group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-group row group2">
    <label for="inputPassword3" class="col-sm-2 form-control-label ">Name</label>
    <div class="col-sm-10">
      <%= form.text_field :name, class: 'form-control subject'%>
    </div>
  </div>

    <div class="form-group row m-t-md">
      <div class="col-sm-offset-2 col-sm-10">
          <%= form.submit class: 'btn btn-fw primary'%>
      </div>
  </div>

<% end %>

app/views/admins_groups/edit.html.erb
<div class="padding">
    <div class="box">
        <div class="box-header">
             <h2>Editing Admins Group</h2>
        </div>
        <div class="box-divider m-0"></div>
            <div class="box-body">
                <%= render 'form', admins_group: @admins_group %>
            </div>
    </div>
    <%= link_to 'Show', @admins_group %> |
<%= link_to 'Back', admins_groups_path %>
</div>

app/views/admins_groups/group_roles.html.erb
<div class="padding">
    <h6>Group roles for <%= @group_name %></h6>
    <%= form_tag edit_group_roles_url, method: :post do  %>
    <%= hidden_field_tag 'groupid',params[:id] %>
        <div class="row m-b">
            <% @roles.each do |role| %>
                <div class="col-sm-4">
                    <div class="box">
                        <div class="box-header primary">
                            <h3><%= (role.caption) %></h3>
                        </div>
                        <div class="box-body">
                            <% Role.where(:caption => role.caption).all.each do |roles| %>
                            <% @is_checked = @assignments.where(:role_id => roles.id).first %>
                            <label class="md-check"> <%= check_box_tag 'role[]', roles.id, (checked = true if @is_checked != nil) %> <i class="green"></i> <%= (roles.name) %> </label>
                           <br>
                            <% end %>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
    <%= content_tag :button, :type => :submit, class: 'btn btn-fw dark' do %>Update Roles<%end%>
    <% end %>
</div>

app/views/admins_groups/index.html.erb
<div class="direct-chat-msg right right2"> <!--class right2 for this style-->
  <div class="direct-chat-text direct2 " data-lrchatext-msgid="3">Admins Groups</div> <!--class direct2 for this style-->
    <% if current_user and current_user.roleid == 1 %>
      <%= link_to 'New Admins Group', new_admins_group_path, {:class => 'btn btn-fw accent accent2'} %>
    <% end %>
</div>
<div class="padding">
  <div class="box">
    <div class="table-responsive table2">
      <table class="table m-b-none" ui-jp="footable" data-filter="#filter" data-page-size="5">
        <thead>
          <tr>
            <th data-toggle="true">Name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @admins_groups.each do |admins_group| %>
            <tr>
                <td><%= admins_group.name %></td>
                <td><%= link_to 'Show', admins_group, :class => "md-btn md-flat m-b-sm w-xs text-warning" %>
                  <%= link_to 'Edit', edit_admins_group_path(admins_group), :class => "md-btn md-flat m-b-sm w-xs text-warning" %>
                  <%= link_to 'Edit Roles', group_roles_path(:id => admins_group.id), :class => "md-btn md-flat m-b-sm w-xs text-warning" %>
                <%= link_to 'Destroy', admins_group, method: :delete, data: { confirm: 'Are you sure?' },:class => "md-btn md-flat m-b-sm w-xs text-warning" %></td>         
            </tr>
          <% end %>          
        </tbody>
        <tfoot class="hide-if-no-paging">
          <tr>
            <td colspan="5" class="text-center">
              <ul class="pagination"></ul>
            </td>
          </tr>
        </tfoot>
      </table>
    </div>
  </div>
</div>
<!-- ############ PAGE END-->

app/views/admins_groups/new.html.erb
<div class="padding">
    <div class="box">
        <div class="box-header">
             <h2>New Admins Group</h2>
        </div>
        <div class="box-divider m-0"></div>
            <div class="box-body">
                <%= render 'form', admins_group: @admins_group %>
            </div>
    </div>
    <%= link_to 'Back', admins_groups_path %>
</div>
                

app/views/admins_groups/show.html.erb
<div class="padding">
      <div class="box">
        <div class="box-header">
          <h3>Admins Group</h3>
        </div>
        <table class="table">
          <thead>
            <tr>
              <th>Name</th>
              <td><%= @admins_group.name %></td>
            </tr>
          </thead>
        </table>
      </div>
      <%= link_to 'Edit', edit_admins_group_path(@admins_group) %> |
      <%= link_to 'Back', admins_groups_path %>
</div>